<?xml version="1.0"?>
<robot name="kai" xmlns:xacro="http://ros.org/wiki/xacro">
  <!--Base platform-->
  <link name="base_platform_link">
    <collision>
      <origin xyz="0 0 ${base_platform_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${base_platform_depth} ${base_platform_width} ${base_platform_height}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${base_platform_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${base_platform_depth} ${base_platform_width} ${base_platform_height}" />
      </geometry>
      <material name="black" />
    </visual>

    <xacro:box_inertia mass="${base_platform_mass}" width="${base_platform_width}"
      depth="${base_platform_depth}" height="${base_platform_height}" />
  </link>

  <joint name="base_fixed_joint" type="fixed">
    <parent link="base_platform_link" />
    <child link="base_cylinder_link" />
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 ${base_platform_height}" rpy="0 0 0"/>
  </joint>


  <link name="base_cylinder_link">
    <collision>
      <origin xyz="0 0 ${base_cylinder_length/2}" rpy="0 0 0" />
      <geometry>
        <box size="${base_cylinder_radius} ${base_cylinder_radius} ${base_cylinder_length/2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${base_cylinder_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${base_cylinder_length}" radius="${base_cylinder_radius}"/>
      </geometry>
      <material name="blue" />
    </visual>

    <xacro:cylinder_center_inertia mass="${base_cylinder_mass}" radius="${base_cylinder_radius}" length="${base_cylinder_length}" />

  </link>

  <joint name="base_pole_joint" type="continuous">
    <parent link="base_cylinder_link" />
    <child link="pole_link" />
    <origin xyz="0 0 ${base_cylinder_length}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
  </joint>
 
 <link name="pole_link">
    <collision>
      <origin xyz="0 0 ${pole_length/2}" rpy="0 0 0" />
      <geometry>
        <box size="${pole_radius} ${pole_radius} ${pole_length}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${pole_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${pole_length}" radius="${pole_radius}" />
      </geometry>
      <material name="red" />
    </visual>

    <xacro:cylinder_center_inertial mass="${pole_mass}" radius="${pole_radius}" length="${pole_length}" />
  </link>


  <joint name="pole_arm_joint" type="revolute">
    <parent link="pole_link"/>
    <child link="arm_link" />
    <origin xyz="0 0 ${pole_length}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <limit effort="1000" lower="-2.5" upper="2.5" velocity="0.6" />
  </joint>

  <link name="arm_link">
     <collision>
       <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0" />
      <geometry>
        <box size="${arm_radius} ${arm_radius} ${arm_length}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${arm_length}" radius="${arm_radius}" />
      </geometry>
      <material name="orange" />
    </visual>

    <xacro:cylinder_end_inertial mass="${arm_mass}" radius="${arm_radius}" length="${arm_length}" />
  </link> 

</robot>
